# <b>■ 딥러닝 수업</b>
    딥러닝으로 할 수 있는 것
    
    인공지능의 눈 : CNN
        예) 불량품 선별, 미술작품 스타일 변환, 의료질병 판별 등
    
    인공지능의 입과 귀 : RNN
        예) 시계열 신경망을 만들어서 주가 예측, 번역, 작곡, 챗봇개발 등
        
## <b>■ 딥러닝이란</b>
    Wikipedia : 여러 비선형변환 기법의 조합을 통해 높은 수준의 추상화를 시도하는 기계학습 알고리즘의 한 종류
    
    머신러닝의 종류 3가지
        1. 지도학습
            신경망 (층이 깊은 신경망을 딥러닝이라 한다)
            
        2. 비지도학습
        3. 강화학습
        
    머신러닝과 딥러닝의 차이
        * 머신러닝으로 기계를 학습시키려면 정형화된 데이터가 있어야 한다.
                                  ↓
          정형화된 데이터를 만들려고 판다스를 공부했다.
              정형화된 데이터를 만드는 것이 상당한 노동력이 들어가는 일이다.
    
        * 딥러닝은 이미지를 신경망에 보여주기만 한다. 스스로 학습을 해서 그 이미지를 알아볼 수 있는 상태가 되는 것.

<center><b>머신러닝</b></center>

![머신러닝](http://cfile295.uf.daum.net/image/21970D33596B26A801530F)
<br><br>
<center><b>딥러닝</b></center>

![딥러닝](http://cfile271.uf.daum.net/image/214E0D33596B2682078B1D)

## <b>■ 딥러닝 기술을 이용해서 현업에서 하고 있는 일들</b>
    1. 공항에서 물품 검색대에 물건을 CNN으로 판별하여 위반되는 물품이 있는지 검사하는 신경망 개발
    2. 의료쪽에서는 x-ray 사진과 의료영상 사진의 질병 여부를 컴퓨터가 판별
    3. 물품(의류, 섬유 등)의 불량품을 판별하는 신경망 개발 + 인터페이스
    4. 자율 주행 자동차에서의 사물 인식
    5. 주가 예측 신경망 개발
    6. 외국어 번역 신경망
    7. 인공지능 변호사 (법률책 -> 신경망 -> 판결)
    8. 음악 작곡 신경망 (Gan) -> Amazon 키보드
    
## <b>■ Numpy 배열 생성하기 </b>
    numpy : python 언어에서 기본적으로 지원하지 않는 배열(array) 혹은 행렬(matrix)의 계산을 쉽게 해주는 라이브러리
            머신러닝에서 많이 사용하는 선형대수학에 관련된 수식들을 python에서 쉽게 프로그래밍 할 수 있게 해준다.

### ※ 문제1. 아래의 행렬을 numpy로 만드시오

In [2]:
import numpy as np
a=[1,2,3,4]
a = np.array(a).reshape((2,2))
a

array([[1, 2],
       [3, 4]])

### ※ 문제2. 위의 a 행렬의 각 요소에 숫자 5를 더하시오

In [3]:
a+5

array([[6, 7],
       [8, 9]])

    numpy에서는 형상이 다른 배열끼리도 계산을 할 수 있다.
    위의 경우처럼 숫자 5가 2x2 행렬로 확대된 후 연산이 이루어지는 것을 브로드캐스트(broadcast)라고 한다.
    numpy가 제공하는 브로드캐스트 기능 덕분에 형상이 다른 배열끼리 연산을 스마트하게 할 수 있다.

### ※ 문제3. 아래의 브로드캐스트 기능을 numpy로 구현하시오

In [4]:
a*10

array([[10, 20],
       [30, 40]])

### ※ 문제4. 아래의 행렬식을 numpy로 구현하시오
$$\begin{pmatrix}
    1 & 3 & 7 \\
    1 & 0 & 0 \\
    \end{pmatrix}+
    \begin{pmatrix}
    0 & 0 & 5 \\
    7 & 5 & 0 \\
    \end{pmatrix}
    $$

In [5]:
import numpy as np
a = np.array([1,3,7,1,0,0]).reshape((2,3))
b = np.array([0,0,5,7,5,0]).reshape((2,3))
a+b

array([[ 1,  3, 12],
       [ 8,  5,  0]])