### <b>■ 기계가 직접 학습해서 가중치(W)를 알아내게끔 하는 방법</b>
#### 예제1. 아래의 두 행렬을 생성하시오
$$x=\begin{bmatrix} -1 & 0 & 0 \\ -1 & 0 & 0 \\ -1 & 0 & 1 \\ -1 & 1 & 1 \\ \end{bmatrix} \\ w = \begin{bmatrix} 0.3 \\ 0.4 \\ 0.1 \\ \end{bmatrix}$$

In [29]:
import numpy as np
x = np.array([-1,0,0,-1,1,0,-1,0,1,-1,1,1]).reshape(4,3)
w = np.array([0.3,0.4,0.1]).reshape(3,1)
x, w

(array([[-1,  0,  0],
        [-1,  1,  0],
        [-1,  0,  1],
        [-1,  1,  1]]),
 array([[0.3],
        [0.4],
        [0.1]]))

#### 예제2. 위의 $x$값과 $w$값을 이용해서 아래와 같이 계산하시오
$$ \begin{bmatrix} -1 & 0 & 0 \end{bmatrix} \cdot \begin{bmatrix} 0.3 & 0.4 & 0.1 \\ \end{bmatrix} = \begin{bmatrix} -0.3 & 0 & 0 \\ \end{bmatrix} $$

In [30]:
x[0]*w.T

array([[-0.3,  0. ,  0. ]])

#### 예제3. 위에서 곱해서 나온 숫자들 3개를 다 더하시오

In [31]:
np.sum(x[0]*w.T)

-0.3

    모든 프로그래밍은 함수로 구성되어져 있다.
        1. 로직을 함수로 생성
        2. 비슷한 기능을 하는 함수를 모아서 클래스 생성
        3. 클래스를 모듈(파일이름.py)로 저장해서 import로 호출해서 사용
    위의 3가지 방법으로 프로그래밍 하는 것을 습관화시켜야 한다.
    
    

#### 예제4. 위의 코드를 predict라는 함수로 생성해서 아래와 같이 실행되게 하시오
```python
print(predict(x,w))
-0.3
```

In [32]:
def predict(x,w):
    a = np.sum(x*w.T)
    return a
predict(x[0],w)

-0.3

#### 예제5. 입력값 4개의 k 값을 다 출력하시오 (for문 돌려서 생성)

In [7]:
for i in range(len(x)):
    print(predict(x[i],w.T))

-0.3
0.10000000000000003
-0.19999999999999998
0.20000000000000004


#### 예제6. 아래의 k값이 step_function 함수에 들어오면 결과로 0과 1이 출력되게 하시오

In [9]:
for i in range(len(x)):
    if predict(x[i],w)>0:
        print(f"{predict(x[i],w)} ---> 1")
    else:
        print(f"{predict(x[i],w)} ---> 0")

-0.3 ---> 0
0.10000000000000003 ---> 1
-0.19999999999999998 ---> 0
0.20000000000000004 ---> 1


In [19]:
def step_func(x):
    y = np.array(x>0) # 입력된 값이 True, False
    return y.astype(np.int)

def predict(x,w):
    a = np.sum(x*w.T)
    return a

for inputs in x:
    k = predict(inputs,w)
    print(step_func(k))

0
1
0
1


#### 예제7. 위에서 출력된 f(k)값과 target의 차이(오차)를 출력하시오

In [20]:
target = np.array([0,0,0,1]).reshape(4,1)
for inputs in x:
    k = predict(inputs, w)
    print(target[i]-step_func(k))

[1]
[0]
[1]
[0]


#### 예제8. predict 함수에 step_func을 포함시키시오

In [21]:
def step_func(x):
    y = np.array(x>0) 
    return y.astype(np.int)

def predict(x,w):
    a = np.sum(x*w.T)
    return step_func(a)

for i in range(len(x)):
    cost = target[i] - predict(x[i],w)
    print(cost)

[0]
[-1]
[0]
[0]


#### 예제9. 위의 코드에 가중치 w값을 갱신하는 아래의 식을 추가하고 갱신되는 가중치 w를 출력한다

In [40]:
import numpy as np
x = np.array([-1,0,0,-1,1,0,-1,0,1,-1,1,1]).reshape(4,3)
w = np.array([0.3,0.4,0.1]).reshape(3,1)

def step_func(x):
    y = np.array(x>0) 
    return y.astype(np.int)

def predict(x,w):
    a = np.sum(x*w.T)
    return step_func(a)

lr = 0.05
for i in range(len(x)):
    cost = target[i] - predict(x[i],w)
#     print(w.shape)
    w = w + np.array([lr * x[i] * cost]).T
#     print(np.array([lr*x[i]*cost]).shape)
    print(w)

[[0.3]
 [0.4]
 [0.1]]
[[0.35]
 [0.35]
 [0.1 ]]
[[0.35]
 [0.35]
 [0.1 ]]
[[0.35]
 [0.35]
 [0.1 ]]


#### 예제10. 가중치가 더이상 갱신되지 않을 때 멈출 수 있도록 하시오

In [43]:
import numpy as np
x = np.array([-1,0,0,-1,1,0,-1,0,1,-1,1,1]).reshape(4,3)
w = np.array([0.3,0.4,0.1]).reshape(3,1)
target = np.array([0,0,0,1]).reshape(4,1)

def step_func(x):
    y = np.array(x>0) 
    return y.astype(np.int)

def predict(x,w):
    a = np.sum(x*w.T)
    return step_func(a)

lr = 0.05
while 1:
    cnt = 0
    for i in range(len(x)):
        cost = target[i] - predict(x[i],w)
        if cost != 0:
            w = w + np.array([lr * x[i] * cost]).T
        elif cost:
            continue
        cnt += cost
    if cnt == 0:
        break
print(w)

[[0.4]
 [0.3]
 [0.1]]


### ※ 문제21. 위의 코드를 이용해서 and_pcn이라는 함수를 생성하시오
```python
print(and_pcn(x,t))
[[0.4]
 [0.3]
 [0.1]]
```

In [45]:
import numpy as np
x = np.array([-1,0,0,-1,1,0,-1,0,1,-1,1,1]).reshape(4,3)
w = np.array([0.3,0.4,0.1]).reshape(3,1)
target = np.array([0,0,0,1]).reshape(4,1)

def and_pcn(x,t):
    w = np.random.randn(3,1)
    
    def step_func(x):
        y = np.array(x>0) 
        return y.astype(np.int)

    def predict(x,w):
        a = np.sum(x*w.T)
        return step_func(a)

    lr = 0.05
    while 1:
        cnt = 0
        for i in range(len(x)):
            cost = t[i] - predict(x[i],w)
            if cost != 0:
                w = w + np.array([lr * x[i] * cost]).T
            elif cost:
                continue
            cnt += cost
        if cnt == 0:
            break
    return w

and_pcn(x,target)

array([[ 0.65165719],
       [-0.31662686],
       [ 0.78514216]])

### ※ 문제22. 위의 함수를 모듈로 만들어서 아래와 같이 실행될 수 있게 하시오
```python
import pcn
```

In [45]:
import numpy as np
x = np.array([-1,0,0,-1,1,0,-1,0,1,-1,1,1]).reshape(4,3)
w = np.array([0.3,0.4,0.1]).reshape(3,1)
target = np.array([0,0,0,1]).reshape(4,1)

def pcn(x,t):
    w = np.random.randn(3,1)
    
    def step_func(x):
        y = np.array(x>0) 
        return y.astype(np.int)

    def predict(x,w):
        a = np.sum(x*w.T)
        return step_func(a)

    lr = 0.05
    while 1:
        cnt = 0
        for i in range(len(x)):
            cost = t[i] - predict(x[i],w)
            if cost != 0:
                w = w + np.array([lr * x[i] * cost]).T
            elif cost:
                continue
            cnt += cost
        if cnt == 0:
            break
    return w

and_pcn(x,target)

array([[ 0.65165719],
       [-0.31662686],
       [ 0.78514216]])